steps:

  # Build the container image

  - name: 'gcr.io/cloud-builders/docker'

    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA', '.']

  # Push the container image to Container Registry

  - name: 'gcr.io/cloud-builders/docker'

    args: ['push', 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

    entrypoint: gcloud

    args:

    - 'run'

    - 'deploy'

    - 'urlService'

    - '--image'

#    - 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
    -  'gcr.io/shortenurl-project-421309/url-shortener:shorturl'

    - '--region'

#    - '$_REGION'
    -  'us-central1'

    - '--allow-unauthenticated'

images:

  - 'gcr.io/$_PROJECT_ID/urlService:$COMMIT_SHA'