server:
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///postgres
    username: postgres
    password: Mandil123
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: shortenurl-project-421309:us-central1:postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
